trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: k6-load-test@0
    inputs:
      filename: 'capsflightLaunchpad.js'
    workingDirectory: $(System.DefaultWorkingDirectory)/performance
    env:
     K6_USERNAME: $(K6_USERNAME)
     K6_PASSWORD: $(K6_PASSWORD)

  - task: PublishHtmlReport@1
    condition: succeededOrFailed()
    inputs:
      reportDir: "$(System.DefaultWorkingDirectory)/performance/result.html"
      tabName: "K6 Performance"
     
