trigger:
  - main
stages:
  - stage: E2E_test
    displayName: Run WDI5 Work Zone tests on BrowserStack
    jobs:
      - job: build
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: BrowserStackConfig@0
            inputs:
              BrowserStackServiceEndPoint: 'BrowserStack'
          - script: |
              echo  BROWSERSTACK_BUILD_NAME=$(System.DefinitionName)-$(Build.BuildId)
              npm install
              npm run wdi5:browserstack
            workingDirectory: $(System.DefaultWorkingDirectory)/e2e
            env:
              wdi5_username: $(wdi5_username)
              wdi5_password: $(wdi5_password)
              BASE_URL: $(URL_LPD)
              BROWSERSTACK_BUILD_NAME: azure-cap-sflight-devops (2)-$(Build.BuildId)
            displayName: 'Run BrowserStack'
            
          # - task: BrowserStackStopLocal@0


          - task: BrowserStackResults@1
            inputs:
              browserstackProduct: 'automate'
