trigger:
  - main
stages:
  - stage: E2E_test
    displayName: Run WDI5 Work Zone tests on BrowserStack
    jobs:
      - template: azure-pipelines/templates/jobs/browserstack-test.yml
        parameters: 
          scriptName: wdi5:browserstack

      # - job: build
      #   pool:
      #     vmImage: "ubuntu-latest"
      #   steps:
      #     - task: BrowserStackConfig@0
      #       inputs:
      #         BrowserStackServiceEndPoint: 'BrowserStack'
      #     - script: |
      #         echo "$BROWSERSTACK_BUILD_NAME"
      #         npm install
      #         npm run wdi5:browserstack
      #       workingDirectory: $(System.DefaultWorkingDirectory)/e2e
      #       env:
      #         wdi5_username: $(wdi5_username)
      #         wdi5_password: $(wdi5_password)
      #         BASE_URL: $(URL_LPD)
      #         BROWSERSTACK_BUILD_NAME: $(BROWSERSTACK_BUILD_NAME)
      #       displayName: 'Run BrowserStack'
            
      #     # - task: BrowserStackStopLocal@0

      #     - task: PublishPipelineArtifact@1
      #       condition: succeededOrFailed()
      #       inputs: 
      #         targetPath:  "$(System.DefaultWorkingDirectory)/e2e/logs"
      #         artifactType: 'pipeline'
      #         artifactName: 'logs'
      #       displayName: 'Publish logs'

      #     - task: BrowserStackResults@1
      #       condition: 
      #       inputs:
      #         browserstackProduct: 'automate'
