name: cap-sflight-devops
resources:
  containers:
    - container: cfcli
      image: "ppiper/cf-cli"
      options: --user 0:0 --privileged
trigger:
  - main
stages:
  - stage: Build
    displayName: Build MTA for SAP Cloud Platform
    jobs:
      - job: build
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - script: npm install
            displayName: NPM install
          - script: npm run build:cf:sqlite
            displayName: Build MTA
          - publish: $(System.DefaultWorkingDirectory)/mta_archives/.
            artifact: WebApp
            displayName: "Publish archive folder"
  - stage: Deploy
    displayName: Deploy 
    dependsOn:
      - Build
    jobs:
      - job: deploy
        pool:
          vmImage: "ubuntu-latest"
        container: cfcli
        steps:
          - checkout: none
          - download: current
            artifact: WebApp
          - bash: |
              cf login -u "$(CF-USER)" -p "$(CF-PASSWORD)" -a "$(CF-API)" -o "$(CF-ORG)" -s "$(CF-SPACE)"
              cf deploy $(Pipeline.Workspace)/WebApp/*.mtar -f
