name: cap-sflight-devops
resources:
  containers:
  - container: cfcli
    image: 'ppiper/cf-cli'
    options: --user 0:0 --privileged
trigger:
- main

stages:
- stage: Build
  displayName: Build MTA for SAP Cloud Platform
  jobs:
    - job: build
      steps: 
        


- stage: Acceptance
  displayName: Build MTA for SAP Cloud Platform
#   jobs:
#     - job: build
#       pool:
#         vmImage: 'ubuntu-latest'
#       steps:  


- stage: Compliance
  displayName: Build MTA for SAP Cloud Platform
#   jobs:
#     - job: build
#       pool:
#         vmImage: 'ubuntu-latest'
#       steps:  


- stage: Release
  displayName: Build MTA for SAP Cloud Platform
#   jobs:
#     - job: build
#       pool:
#         vmImage: 'ubuntu-latest'
#       steps:  
