parameters:
  vmImage: windows-latest
  scriptName: wdi5:headless
  runJob: false

jobs:
  - job: WDI5Tests
    condition: eq(${{ parameters.runJob }}, 'true')
    pool:
      vmImage: ${{ parameters.vmImage }}
      # vmImage: macOS-latest
    steps:
      - pwsh: |
          npm install --omit=dev
          npm run ${{ parameters.scriptName }}
        workingDirectory: $(System.DefaultWorkingDirectory)/e2e
        env:
          wdi5_username: $(wdi5_username)
          wdi5_password: $(wdi5_password)
          BASE_URL: $(URL_LPD)
        displayName: WDI5 test

      - task: PublishPipelineArtifact@1
        condition: failed()
        inputs:
          targetPath: "$(System.DefaultWorkingDirectory)/e2e/logs"
          artifactType: "pipeline"
          artifactName: "logs"
        displayName: "Publish logs"

      - task: PublishHtmlReport@1
        condition: succeededOrFailed()
        inputs:
          reportDir: "$(System.DefaultWorkingDirectory)/test-results/e2e/timeline-report.html"
          tabName: "WDI5 Tests"
