name: cap-sflight-devops
trigger:
  - main
stages:
- stage: Scan
  displayName: Security Scan
  jobs:
    - job: scan
      steps:
        - template: templates/steps/snykSecurityScan.yml
          parameters:
              runJob: true