name: cap-sflight-devops
resources:
trigger:
  - main
stages:
  - stage: E2E_tests
    displayName: Perform E2E Tests
    variables:
      - group: e2e-variables
    jobs:
      - template: templates/jobs/performance-test.yml
        parameters:
          filename: performance/capsflightLaunchpad.js
          runJob: true
